package com.phylodata.loader;

import com.phylodata.types.PaperWithExperiment;

import java.nio.file.Path;
import java.util.List;

public class Citations {
    public static void storeCitations(List<PaperWithExperiment> experiments, Path citationsFile) {
        int year = java.time.LocalDate.now().getYear();

        try (java.io.BufferedWriter handle = java.nio.file.Files.newBufferedWriter(citationsFile)) {
            handle.write(String.format("@comment{\n\tAutomatically generated by PhyloData.\n}\n\n"));
            handle.write(String.format("@online{phylodata%d,\n", year));
            handle.write("\ttitle\t= {PhyloData},\n");
            handle.write("\tauthor\t= {Tobia Simon Ochsner},\n");
            handle.write(String.format("\tyear\t= %d,\n", year));
            handle.write("\turl\t= {https://phylodata.com},\n");
            handle.write("}\n");

            for (PaperWithExperiment experiment : experiments) {
                handle.write("\n\n");
                handle.write(experiment.getPaper().getBibtex());
            }
        } catch (java.io.IOException e) {
            throw new RuntimeException("Failed to write citations file: " + e.getMessage(), e);
        }
    }
}
